# Project: Project1
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o camera.o collision.o global.o interaction.o level_generator.o lighting.o player.o shadow.o texture.o tile.o
LINKOBJ  = main.o camera.o collision.o global.o interaction.o level_generator.o lighting.o player.o shadow.o texture.o tile.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -DGLAPI="extern" -DAPIENTRY="" -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32 -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3 -DGLUT_STATIC
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

camera.o: camera.cpp
	$(CPP) -c camera.cpp -o camera.o $(CXXFLAGS)

collision.o: collision.cpp
	$(CPP) -c collision.cpp -o collision.o $(CXXFLAGS)

global.o: global.cpp
	$(CPP) -c global.cpp -o global.o $(CXXFLAGS)

interaction.o: interaction.cpp
	$(CPP) -c interaction.cpp -o interaction.o $(CXXFLAGS)

level_generator.o: level_generator.cpp
	$(CPP) -c level_generator.cpp -o level_generator.o $(CXXFLAGS)

lighting.o: lighting.cpp
	$(CPP) -c lighting.cpp -o lighting.o $(CXXFLAGS)

player.o: player.cpp
	$(CPP) -c player.cpp -o player.o $(CXXFLAGS)

shadow.o: shadow.cpp
	$(CPP) -c shadow.cpp -o shadow.o $(CXXFLAGS)

texture.o: texture.cpp
	$(CPP) -c texture.cpp -o texture.o $(CXXFLAGS)

tile.o: tile.cpp
	$(CPP) -c tile.cpp -o tile.o $(CXXFLAGS)
